noteId = "fc3ead1e-6d00-4d22-9b9d-c9a4271e5f01"
server = "https://bitwarden.brumspace.synology.me"
email = "kathrinviolin99@gmail.com"
secretsFile = ".zshsecrets"

[[files]]
srcFile = "smb-secrets"
destFile = "smb-secrets"
chmod = "0600"
