noteId = "c660a85d-1081-464e-a37f-b396bca432f5"
server = "https://bitwarden.brumspace.duckdns.org"
email = "levente.berky@gmail.com"
secretsFile = ".zshsecrets"

[[files]]
srcFile = "config"
destFile = ".ssh/config"
chmod = "0600"

[[files]]
srcFile = "allowed_signers"
destFile = ".ssh/allowed_signers"
chmod = "0644"

[[files]]
srcFile = "id_ed25519"
destFile = ".ssh/id_ed25519"
chmod = "0600"

[[files]]
srcFile = "id_ed25519.pub"
destFile = ".ssh/id_ed25519.pub"
chmod = "0644"

[[files]]
srcFile = "smb-secrets"
destFile = "smb-secrets"
chmod = "0600"
