keys:
  - &brum age18p2gethkwx0ngntgg8y3jrhfe8qjdqw07hrslchqmyutuw2m8ysqthcyr5
  - &anteater age1revjgg0dv9gs6tdudztfx7e4hxhyrpf0qtqqw8p47ymwf6ymu52s4n27lk
  - &brumstellar age1yf972c6v37du9q67e38nk77ucs89kxg9hxzhv398h2eheq9k0fqqw2cuf9
  - &gamingrig age1xj5rxkfa4xuq3pt0f842wsvmkukcqasjvmh9e7gp90k2n4c7pvusd4ak5p
  - &n100 age1wh6s7yvvpn0rtpalju9jkr0uxmr2xxg3ktvdu4wq3a6ujd8d6fhsnd8w2l
  - &sleeper age1udl52wzj3z5uqmzx4gcacmuhgpes43wz8w4zd99c2eg8ff8ycenqnl2zk6
creation_rules:
  # relative path to the secrets form this file
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *brum
      - *brumstellar
      - *n100
      - *anteater
      - *gamingrig
      - *sleeper
