services:
  # Traefik 3 - Reverse Proxy
  traefik:
    container_name: traefik
    image: traefik:3.1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      t3_proxy:
    #     ipv4_address: 192.168.90.254 # You can specify a static IP
      socket_proxy:
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:8080
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --api=true
      - --api.dashboard=true
      - --entrypoints.websecure.forwardedHeaders.trustedIPs=$LOCAL_IPS
      - --log=true
      # - --log.filePath=/logs/traefik.log
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      # - --accessLog=true
      # - --accessLog.filePath=/logs/access.log
      # - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      # - --accessLog.filters.statusCodes=204-299,400-499,500-599
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://socket-proxy:2375 # Enable for Socket Proxy. Disable otherwise.
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=t3_proxy 
      # - --entrypoints.websecure.http.tls.options=tls-opts@file

      - --certificatesresolvers.duckdns-letsencryp.acme.dnschallenge=true
      - --certificatesresolvers.duckdns-letsencryp.acme.dnschallenge.provider=duckdns
      - --certificatesresolvers.duckdns-letsencryp.acme.dnschallenge.delaybeforecheck=20
      - --certificatesresolvers.duckdns-letsencryp.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.duckdns-letsencryp.acme.email=levente.berky@gmail.com

      - --entrypoints.websecure.http.tls.certresolver=duckdns-letsencryp
      - --entrypoints.websecure.http.tls.domains[0].main=$DOMAINNAME_1
      - --entrypoints.websecure.http.tls.domains[0].sans=*.$DOMAINNAME_1
      # - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory
      # - --providers.file.watch=true # Only works on top level files in the rules folder
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      # - ../appdata/traefik/rules:/rules # Dynamic File Provider directory
      - letsencrypt:/letsencrypt # Certs File 
      # - ../logs/traefik:/logs # Traefik logs
    environment:
      - TZ=$TZ
      # - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token    
      # - HTPASSWD_FILE=/run/secrets/basic_auth_credentials # HTTP Basic Auth Credentials
      # - DOMAINNAME_1 # Passing the domain name to traefik container to be able to use the variable in rules. 
    # secrets:
      - DUCKDNS_TOKEN=$DUCKDNS_TOKEN
    #   - cf_dns_api_token
    #   - basic_auth_credentials
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=websecure"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME_1`)"
      # Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      # Middlewares
      # - "traefik.http.routers.traefik-rtr.middlewares=middlewares-basic-auth@file" # For Basic HTTP Authentication

volumes:
  letsencrypt:

