search_submodules = false
recursive_submodules = false
default_session = "home"

[[search_dirs]]
path = "~/Documents"
depth = 1

[[search_dirs]]
path = "~/config"
depth = 1

[[search_dirs]]
path = "~/Documents/Klara"
depth = 1

